### ISSUE TITLE
Difficulty when creating peers and orderers

### ISSUE THREAD

**Issue by sapient** [kfsoftware/hlf-operator#65]
Hi, I have a fresh EKS instance setup, operator is 1.5.0 and plugin is 1.5.1.

I started off following the tutorial with some light modifications to suit my setup, however when I got to the channel creation point, I received the following error

```
$ kubectl hlf channel generate --output=demo.block --name=demo --organizations Org1MSP --ordererOrganizations OrdererMSP                                                                                                                                                                                                

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1fbca5e]

goroutine 1 [running]:
github.com/kfsoftware/hlf-operator/controllers/utils.ParseX509Certificate({0x36002e8, 0x0, 0x0})
	github.com/kfsoftware/hlf-operator/controllers/utils/utils.go:73 +0x1e
github.com/kfsoftware/hlf-operator/kubectl-hlf/cmd/channel.generateChannelCmd.run({{0x7ff7bfeff5f1, 0x4}, {0xc00052fd10, 0x1, 0x1}, {0xc00052fd20, 0x1, 0x1}, {0x7ff7bfeff5df, 0xa}})
	github.com/kfsoftware/hlf-operator/kubectl-hlf/cmd/channel/generate.go:62 +0x1fd
github.com/kfsoftware/hlf-operator/kubectl-hlf/cmd/channel.newGenerateChannelCMD.func1(0xc0003ae840, {0x25053f5, 0x6, 0x6})
	github.com/kfsoftware/hlf-operator/kubectl-hlf/cmd/channel/generate.go:190 +0xd8
github.com/spf13/cobra.(*Command).execute(0xc0003ae840, {0xc0005317a0, 0x6, 0x6})
	github.com/spf13/cobra@v1.0.0/command.go:842 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc00016c2c0)
	github.com/spf13/cobra@v1.0.0/command.go:950 +0x3ad
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	github.com/kfsoftware/hlf-operator/kubectl-hlf/main.go:22 +0x6a
```

I took down all the nodes and started again by running the following commands

```
kubectl hlf ca create --storage-class=gp2 --capacity=2Gi \
    --name=org1-ca --enroll-id=enroll --enroll-pw=enrollpw --hosts org1-ca.xnet.xfd.io  

kubectl hlf ca register --name=org1-ca --user=peer --secret=peerpw --type=peer \
    --enroll-id enroll --enroll-secret=enrollpw --mspid Org1MSP

kubectl hlf peer create --statedb=couchdb --image=hyperledger/fabric-peer --version=2.4.1 --storage-class=gp2 \
    --enroll-id=peer --mspid=Org1MSP --enroll-pw=peerpw --capacity=5Gi --name=org1-peer0 --ca-name=org1-ca.default \
    --hosts=org1-ca.xnet.xfd.io
```

However when I checked my cluster, there was never any pods created for the peer. I pushed on anyway and ran the appropriate commands for the orderer, again, no orderer pod was created while I got the following result 

```
INFO[0005] Peer org1-peer0 created on namespace default
```

Any help would be appreciated!
Thanks

**Comment by sapient** [comment]
I have managed to find this error message in the manage pod, but I am not sure what to do with the information.

``` 
time="2022-03-30T13:24:28Z" level=warning msg="Failed to update status to FAILED: FabricPeer.hlf.kungfusoftware.es \"peer0\" is invalid: [status.conditions: Required value, status.message: Required value]"
```

This is the message I receive when I run the following command
```
kubectl hlf peer create --statedb=couchdb --image=hyperledger/fabric-peer --version=2.4.1 \
    --enroll-id=peer --enroll-pw=peerpw --mspid=Org1MSP --capacity=5Gi --ca-name=org1-ca.default \
    --name=peer0 --hosts=peer0.xnet.xfd.io
```

**Comment by dviejokfs** [comment]
Hi @sapient 

Could you send us the hlf-operator logs? Here's my email dviejo@kungfusoftware.es

Thanks!

**Comment by dviejokfs** [comment]
Closing this issue @sapient, if the problem arises please join the discord channel so we can help you:

https://github.com/hyperledger-labs/hlf-operator#discord
